In [3]:
import numpy as np

In [4]:
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [5]:
x = np.delete(x, [0,4])
print(x)

[2 3 4]


In [6]:
x = np.delete(x, [0])
print(x)

[3 4]


In [7]:
x = np.delete(x, [0,1])
print(x)

[]


In [8]:
x = np.delete(x, [0,4])
print(x)

[]


/Users/rohitluthra/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: in the future out of bounds indices will raise an error instead of being ignored by `numpy.delete`.
  """Entry point for launching an IPython kernel.


In [9]:
y = np.arange(1,10).reshape(3,3)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
z = np.delete(y, 0, axis=0)
print(z)

[[4 5 6]
 [7 8 9]]


In [13]:
z = np.delete(y, 0, axis=1)
print(z)

[[2 3]
 [5 6]
 [8 9]]


In [14]:
y = np.arange(1,10).reshape(3,3)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
q = np.delete(y, [0,2], axis =1)
print(q)

[[2]
 [5]
 [8]]


In [19]:
y = np.append(y, [7,8,6]).reshape(7,2)
print(y)

[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 7]
 [8 7]
 [8 6]]


In [23]:
y = np.append(y, [[1],[1],[1],[1],[1],[1],[1]], axis =1)
print(y)

[[1 2 1 1 1]
 [3 4 1 1 1]
 [5 6 1 1 1]
 [7 8 1 1 1]
 [9 7 1 1 1]
 [8 7 1 1 1]
 [8 6 1 1 1]]


In [26]:
# We create a rank 1 ndarray 
x = np.array([1,2])

# We create a rank 2 ndarray 
Y = np.array([[3,4],[5,6]])

# We print x
print()
print('x = ', x)

# We print Y
print()
print('Y = \n', Y)

# We stack x on top of Y
z = np.vstack((x,Y))

# We stack x on the right of Y. We need to reshape x in order to stack it on the right of Y. 
w = np.hstack((Y,x.reshape(2,1)))

# We print z
print()
print('z = \n', z)

# We print w
print()
print('w = \n', w)


x =  [1 2]

Y = 
 [[3 4]
 [5 6]]

z = 
 [[1 2]
 [3 4]
 [5 6]]

w = 
 [[3 4 1]
 [5 6 2]]
