In [9]:
import numpy as np
import time

In [10]:
variable = np.random.random(100000)
start = time.time()

In [11]:
print(sum(variable)/len(variable))
print(time.time() - start)

0.49932880644255934
0.031419992446899414


In [12]:
np.mean(variable)
print(time.time() - start)

0.04118180274963379


In [13]:
# np Array
newArray = np.array([1,2,3,4,5])

In [14]:
print(newArray)
print(type(newArray))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [15]:
newArray.shape

(5,)

In [16]:
newArray.dtype

dtype('int64')

In [17]:
randomArray = np.random.rand(3,4)
print(randomArray)

[[0.36657089 0.12638269 0.87002248 0.82107978]
 [0.01466123 0.75960819 0.53932874 0.68999118]
 [0.28617694 0.03441686 0.73436027 0.30075287]]


In [19]:
print(randomArray.shape, randomArray.dtype, randomArray.size)

(3, 4) float64 12


In [20]:
randomArray_1 = np.array([1,2,"Hello"])
print(randomArray_1.shape, randomArray_1.dtype, randomArray_1.size, type(randomArray_1))

randomArray_2 = np.array(["Hello", "World"])
print(randomArray_2.shape, randomArray_2.dtype, randomArray_2.size, type(randomArray_2))



(3,) <U21 3 <class 'numpy.ndarray'>
(2,) <U5 2 <class 'numpy.ndarray'>


In [21]:
randomArray_2 = np.array([1,2.5,5,6.7])
print(randomArray_2.shape, randomArray_2.dtype, randomArray_2.size, type(randomArray_2))


(4,) float64 4 <class 'numpy.ndarray'>


In [25]:
randomArray_2 = np.array([1,2.5,5,6.7], dtype = np.int64)
print(randomArray_2.shape, randomArray_2.dtype, randomArray_2.size, type(randomArray_2))


(4,) int64 4 <class 'numpy.ndarray'>


In [26]:
savingFile = np.array([1,2,3,4,5,5,67,7])
np.save('mySavedArray', savingFile) # mySavedArray.npy

In [27]:
np.load("mySavedArray.npy")

array([ 1,  2,  3,  4,  5,  5, 67,  7])