In [1]:
import numpy as np
currentList = np.array([1,213,546,356,76])

In [3]:
zeroArray = np.zeros((4,5))
print(zeroArray, zeroArray.dtype)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] float64


In [5]:
oneArray = np.ones((4,5))
print(oneArray, oneArray.dtype)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] float64


# Full

In [7]:
fullArray = np.full((4,4), 10.)
print(fullArray, fullArray.dtype)

[[10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]] float64


In [8]:
identityMatrix = np.eye(5)
print(identityMatrix, identityMatrix.dtype)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] float64


In [9]:
diagonalMatrix = np.diag([10,20,30,50])
print(diagonalMatrix, diagonalMatrix.dtype)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]] int64


In [10]:
 # start, stop, step
    # if only one then it is referred to as "stop" value
random= np.arange(10)
print(random)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
# first value(inclusive) is start the last is stop(exclusive)
random= np.arange(10,40)
print(random)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39]


In [13]:
#first value(inclusive) is start the last is stop(exclusive)
random= np.arange(10,40,2)
print(random)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]


In [21]:
# for non integer steps
random = np.linspace(1, 40, 40)
print(random)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40.]


In [20]:
# for non integer steps
random = np.linspace(1, 40, 40, endpoint= False)
print(random)

[ 1.     1.975  2.95   3.925  4.9    5.875  6.85   7.825  8.8    9.775
 10.75  11.725 12.7   13.675 14.65  15.625 16.6   17.575 18.55  19.525
 20.5   21.475 22.45  23.425 24.4   25.375 26.35  27.325 28.3   29.275
 30.25  31.225 32.2   33.175 34.15  35.125 36.1   37.075 38.05  39.025]


In [28]:
reshapeArray = np.reshape(random, (10,4))
print(reshapeArray)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]
 [17. 18. 19. 20.]
 [21. 22. 23. 24.]
 [25. 26. 27. 28.]
 [29. 30. 31. 32.]
 [33. 34. 35. 36.]
 [37. 38. 39. 40.]]


    #Combining linspace and arange with reshape

In [32]:
temp = np.arange(30).reshape(10,3)
tem = np.linspace(0,20,10, endpoint=False).reshape(10,1)

print(temp, tem)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]] [[ 0.]
 [ 2.]
 [ 4.]
 [ 6.]
 [ 8.]
 [10.]
 [12.]
 [14.]
 [16.]
 [18.]]


In [33]:
x = np.random.random((3,3))
print(x)

[[0.35781054 0.98116171 0.25781244]
 [0.85143097 0.15954045 0.48423822]
 [0.75684572 0.82713699 0.57047186]]


In [38]:
y = np.random.randint(1,12,(3,4))
print(y)

[[ 3  4  3  2]
 [ 1 11  1  2]
 [ 4 11 11 10]]


In [41]:
# prob distribution
normal = np.random.normal(0, 0.1, size=(100,100))
print(normal)

[[ 0.12091074  0.07502343 -0.06098758 ...  0.125066   -0.08932041
  -0.07281122]
 [-0.12629181  0.09841646 -0.06791312 ...  0.09230743  0.12104202
  -0.22822976]
 [ 0.06652565  0.21074765 -0.13559044 ... -0.14758584  0.08916973
   0.01822583]
 ...
 [ 0.09880392  0.12070143 -0.11702716 ...  0.06435464  0.13776154
  -0.07965063]
 [ 0.12551451 -0.16846198 -0.2262297  ...  0.03900362  0.03465121
   0.0132679 ]
 [ 0.02358032  0.15087969  0.05914536 ... -0.01228095 -0.03373164
  -0.02628525]]


In [42]:
print(normal.mean())
print(normal.std())
print(normal.max())
print(normal.min())
print("+ values - ", (normal>0).sum())
print("- values - ", (normal<0).sum())

-0.001274023733632938
0.10093745915530575
0.38351447593822946
-0.41032549991225703
+ values -  4915
- values -  5085
